version: "3.9"

services:
  assignment-service:
    build:
      context: .
    container_name: assignment-service
    ports:
      - "5050:5050"
    env_file:
      - .env.test
    secrets:
      - jwt_public.pem
      - jwt_private.pem
    depends_on:
      assignments-db:
        condition: service_healthy

  assignments-db:
    image: mongo:4.4
    container_name: assignments-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-test-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s

volumes:
  mongo-test-data:

secrets:
  jwt_public.pem:
    file: ./secrets/public.pem
  jwt_private.pem:
    file: ./secrets/private.pem
